"use client";

import { useState } from "react";
import { usePoll } from "@/lib/usePoll";
import { PageHeader } from "@/components/ui/PageHeader";
import { ErrorNote } from "@/components/ui/ErrorNote";
import { Chip } from "@/components/ui/Chip";

interface Step {
  id: string;
  title: string;
  body: string;
  commands: Record<string, string>;
  note?: string;
  optional?: boolean;
}

interface Platform {
  id: string;
  label: string;
  note?: string;
  steps: Step[];
}

interface DeployInfo {
  cluster: string;
  namespace: string;
  oses: { id: string; label: string }[];
  platforms: Platform[];
  connectEnv: { name: string; value: string; note: string }[];
}

/**
 * Deployment.
 *
 * Generated by the backend rather than written into the docs, so it always
 * names this console's own namespace and endpoints. A deployment guide that
 * tells you to connect to the wrong port is worse than no guide.
 */
export default function DeployPage() {
  const { data, error } = usePoll<DeployInfo>("/api/v1/deployment", 0);
  const [platform, setPlatform] = useState("generic");
  const [os, setOS] = useState("macos");

  const active = data?.platforms.find((p) => p.id === platform) ?? data?.platforms[0];

  return (
    <>
      <PageHeader
        title="Deployment"
        subtitle="Everything needed to stand Cilium, Tetragon and this console up on another cluster. No cloud-specific assumptions — pick your platform."
        actions={data && <Chip mono>{data.cluster}</Chip>}
      />

      <ErrorNote error={error} />

      <div className="panel mb-4 flex flex-wrap items-center gap-3 px-4 py-3">
        <div className="flex flex-wrap gap-1">
          {(data?.platforms ?? []).map((p) => (
            <button
              key={p.id}
              onClick={() => setPlatform(p.id)}
              className={`btn ${p.id === platform ? "btn-secondary" : "btn-ghost"} !px-2.5 !py-1.5 !text-[12px]`}
            >
              {p.label}
            </button>
          ))}
        </div>
        <span className="mx-1 h-4 w-px" style={{ background: "var(--hairline)" }} />
        <div className="flex gap-1">
          {(data?.oses ?? []).map((o) => (
            <button
              key={o.id}
              onClick={() => setOS(o.id)}
              className={`btn ${o.id === os ? "btn-secondary" : "btn-ghost"} !px-2.5 !py-1.5 !text-[12px]`}
            >
              {o.label}
            </button>
          ))}
        </div>
      </div>

      {active?.note && (
        <p className="mb-4 max-w-3xl text-[13px] leading-relaxed text-[color:var(--text-secondary)]">
          {active.note}
        </p>
      )}

      <ol className="space-y-4">
        {(active?.steps ?? []).map((s, i) => (
          <li key={s.id} className="panel px-4 py-3">
            <div className="flex items-center gap-2">
              <span
                className="grid h-5 w-5 shrink-0 place-items-center rounded-full text-[11px] font-medium"
                style={{ background: "var(--surface-3)", color: "var(--text-secondary)" }}
              >
                {i + 1}
              </span>
              <h2 className="text-[14px] font-medium">{s.title}</h2>
              {s.optional && <Chip>optional</Chip>}
            </div>
            {s.body && (
              <p className="mt-1.5 max-w-3xl text-[12px] leading-relaxed text-[color:var(--text-secondary)]">
                {s.body}
              </p>
            )}
            <CommandBlock text={s.commands[os] ?? s.commands.all ?? ""} />
            {s.note && (
              <p className="mt-1.5 text-[11px] leading-relaxed text-[color:var(--text-tertiary)]">
                {s.note}
              </p>
            )}
          </li>
        ))}
      </ol>

      <section className="panel mt-5 px-4 py-3">
        <h2 className="text-[14px] font-medium">Connecting the console to a cluster</h2>
        <p className="mt-1 max-w-3xl text-[12px] leading-relaxed text-[color:var(--text-secondary)]">
          These are the only settings that matter. Everything else has a working default.
        </p>
        <table className="mt-3 w-full text-[12px]">
          <tbody>
            {(data?.connectEnv ?? []).map((e) => (
              <tr key={e.name} className="hairline-t align-top">
                <td className="mono py-2 pr-4 whitespace-nowrap">{e.name}</td>
                <td className="mono py-2 pr-4 text-[color:var(--text-secondary)]">{e.value}</td>
                <td className="py-2 text-[color:var(--text-tertiary)]">{e.note}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
    </>
  );
}

function CommandBlock({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  if (!text) return null;
  return (
    <div className="relative mt-2.5">
      <pre
        className="mono overflow-x-auto rounded-lg p-3 text-[11.5px] leading-relaxed"
        style={{ background: "var(--surface-0)", border: "1px solid var(--hairline)", color: "#d8d7cf" }}
      >
        {text}
      </pre>
      <button
        className="btn btn-ghost absolute right-1.5 top-1.5 !px-2 !py-1 !text-[11px]"
        onClick={async () => {
          try {
            await navigator.clipboard.writeText(text);
            setCopied(true);
            setTimeout(() => setCopied(false), 1500);
          } catch {
            /* clipboard blocked — the text is selectable */
          }
        }}
      >
        {copied ? "copied" : "copy"}
      </button>
    </div>
  );
}
